---
title: "Diversity Calculations"
output: html_document
date: "2023-11-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages and Data}
#devtools::install_github("jinyizju/V.PhyloMaker")
#devtools::install_github("GabrielNakamura/Dimensionality_package")
#BiocManager::install("ggtree")
library(tidyverse);library(adespatial);library(vegan);library(ggplot2);library(ggpubr);library(V.PhyloMaker);library(BIOMASS);library(picante);library(ape);library(BiocManager);library(Dimensionality);library(ggtree);library(adiv);library(MuMIn);library(ggfortify);library(scales);library(factoextra);library(GGally);library(corrplot)

tdat <- read.csv("~/Documents/GitHub/FaunalDegradationAGBNew/Data/tdat_frug2_diversity.csv")
metadata <- read.csv("metadata_updated.csv")
frug_tree <- read.tree("~/Documents/Projects/GabonAGB_NSF/frug_tree") #phylogenetic tree
animal_taxa <- read.csv("~/Documents/GitHub/GabonDiversity/Data/animal_taxa.csv")
frug_dat_total <- read.csv("~/Documents/Projects/GabonAGB_NSF/frug_dat_total2.csv")
tdat$Genus[tdat$Genus=="Obletiana"] <- "Obletia"
tdat$Genus[tdat$Genus=="Syzyguim"] <- "Syzygium"
tdat$Genus[tdat$Genus=="Pschotria"] <- "Psychotria"
tdat$Genus[tdat$Genus=="Terminialia"] <- "Terminalia"
tdat$Genus[tdat$Genus=="Dacroydes"] <- "Dacryodes"

tdat <- tdat %>% filter(DispoCode != "NRI_P140", DispoCode !="NRI_P171", DispoCode != "NRI_P066", DispoCode !="NRI_P092", DispoCode != "OLAM_P030", DispoCode !="NRI_P164", DispoCode !="OLAM_P027", DispoCode !="NRI_P072") #remove plots with very poor species identification

animal_taxa_norodents <- animal_taxa %>% filter(Taxa != "Rodent")
nonrodent_species <- animal_taxa_norodents$Animal   

tdat <- tdat %>%
  dplyr::select(
    1:(which(names(tdat) == "Agapornis_swindernianus") - 1),
    any_of(intersect(names(tdat), nonrodent_species))
  )

```

```{r Metadata cleaning}

metadata_soil <- metadata %>% select(T_BULK_DEN, S_BULK_DEN, T_CEC_CLAY, S_CEC_CLAY, T_CLAY, S_CLAY:S_OC)

soil_pca <- princomp(metadata_soil)

summary(soil_pca)

ind<-get_pca_ind(soil_pca)

metadata$SoilPCA <- ind$coord[,1]
metadata$SoilPCA <- scale(metadata$SoilPCA)

tdat2 <- tdat %>% filter(Genus != "Na")
(nrow(tdat)-nrow(tdat2))/nrow(tdat) 


metadata3 <- metadata %>% select(Temp, Prec, Latitude, SoilPCA, VillDist, NightLights, PopDensity) %>% summarise(
  Temp = mean(Temp), Prec = mean(Prec), Latitude = mean(Latitude), SoilPCA = mean(SoilPCA), VillDist = mean(VillDist), NightLights = mean(NightLights), PopDensity = mean(PopDensity)
)

metadata <- metadata[metadata$DispoCode %in% tdat$DispoCode,]
metadata$Elephant[metadata$Elephant=="Ancienne piste/pas d'activite"] <- "1"
metadata$Elephant[metadata$Elephant=="Active"] <- "1"
metadata$Elephant[metadata$Elephant=="Pas d'indice"] <- "0"

metadata_og <- metadata

metadata$VillDist <- scale(metadata$VillDist)
metadata$Temp <- scale(metadata$Temp)
metadata$Prec <- scale(metadata$Prec)
metadata$Latitude <- scale(metadata$Latitude)
metadata$T_OC <- scale(metadata$T_OC)
metadata$T_CEC_CLAY <- scale(metadata$T_CEC_CLAY)
metadata$Elev <- scale(metadata$Elev)
metadata$NightLights <- scale(metadata$NightLights)
metadata$PopDensity <- scale(metadata$PopDensity)

metadata_test <- metadata %>% dplyr::select(VillDist, Temp, Prec, Latitude, SoilPCA, Elev, NightLights, PopDensity)

cor_mat <- cor(metadata_test, use = "pairwise.complete.obs")

corrplot(cor_mat, 
         method = "color",        # color tiles
         type = "upper",          # show only upper triangle
         order = "hclust",        # reorder variables by hierarchical clustering
         addCoef.col = "black",   # add correlation coefficients
         number.cex = 0.7,        # size of numbers
         tl.col = "black",        # text label color
         tl.srt = 45,             # text rotation
         col = colorRampPalette(c("darkred", "white", "darkblue"))(200), # color scale
         diag = FALSE,            # hide the diagonal
         cl.cex = 0.8,            # legend text size
         mar = c(0,0,1,0))        # margins (top margin leaves space for title)

write.csv(metadata, "metadata_cleaned.csv")


```

```{r Calculate Interaction Diversity}
richness_list <- as.list(NULL)
alpha_list <- as.list(NULL)
beta_list <- as.list(NULL)
prop_list <- as.list(NULL)
n_list <- as.list(NULL)
ape_list <- as.list(NULL)
ape_prop_list <- as.list(NULL)
bat_list <- as.list(NULL)
bat_prop_list <- as.list(NULL)
bird_list <- as.list(NULL)
bird_prop_list <- as.list(NULL)
bush_list <- as.list(NULL)
bush_prop_list <- as.list(NULL)
carnivore_list <- as.list(NULL)
carnivore_prop_list <- as.list(NULL)
elephant_list <- as.list(NULL)
elephant_prop_list <- as.list(NULL)
monkey_list <- as.list(NULL)
monkey_prop_list <- as.list(NULL)
rodent_list <- as.list(NULL)
rodent_prop_list <- as.list(NULL)
suidae_list <- as.list(NULL)
suidae_prop_list <- as.list(NULL)
ungulate_list <- as.list(NULL)
ungulate_prop_list <- as.list(NULL)

for(i in 1:25){

tdat_interaction <- tdat2 %>% select(X,DispoCode, Genus, Agapornis_swindernianus:Zosterops_senegalensis) %>% pivot_longer(names_to = "Animal", values_to = "InteractionProbability", cols = Agapornis_swindernianus:Zosterops_senegalensis)

tdat_interaction$InteractionProbability <- rbinom(nrow(tdat_interaction), 1 , tdat_interaction$InteractionProbability) #draw from probability distribution
  
tdat_interaction2 <- tdat_interaction %>% filter(InteractionProbability ==1) %>% unite("Interaction", Genus:Animal, sep="_")

#Richness
div_values_interaction <- tdat_interaction2 %>%select(DispoCode, Interaction) %>%group_by(DispoCode) %>% summarise(richness = length(unique(Interaction))) 

#Alpha Diversity
tdat3_interaction <- tdat_interaction2%>% group_by(DispoCode, Interaction) %>% summarise(InteractionProbability = sum(InteractionProbability)) %>% pivot_wider(names_from = Interaction, values_from = InteractionProbability)
tdat3_interaction[is.na(tdat3_interaction)]<-0
tdat3_interaction<- as.data.frame(tdat3_interaction)
rownames(tdat3_interaction)<- tdat3_interaction$DispoCode
tdat3_interaction <- tdat3_interaction[,-1]
diversity_values_interaction <- vegan::diversity(tdat3_interaction)#calculate alpha diversity values
div_values_interaction$alpha <- diversity_values_interaction

#Beta Diversity
beta_div_interaction <- beta.div(tdat3_interaction, "hellinger", nperm=1000) #calculate beta diversity
beta_values_interaction <- beta_div_interaction$LCBD# calculate local contributions to beta diversity
div_values_interaction$beta <- beta_values_interaction

#Proportion of trees with frugivore interaction

prop_dat2 <- left_join(tdat_interaction, animal_taxa[,c(2,4)], by = "Animal") %>% dplyr::select(DispoCode, InteractionProbability, Taxa,X) %>% group_by(DispoCode, X, Taxa) %>% summarise(Interaction = sum(InteractionProbability)) %>% pivot_wider(names_from = Taxa, values_from = Interaction) %>% dplyr::select(-X)
prop_dat2 <- prop_dat2[,-1]
prop_dat2$Ape[prop_dat2$Ape>0]<-1
prop_dat2$Bat[prop_dat2$Bat>0]<-1
prop_dat2$Bird[prop_dat2$Bird>0]<-1
prop_dat2$BushBaby[prop_dat2$BushBaby>0]<-1
prop_dat2$Carnivore[prop_dat2$Carnivore>0]<-1
prop_dat2$Elephant[prop_dat2$Elephant>0]<-1
prop_dat2$Monkey[prop_dat2$Monkey>0]<-1
#prop_dat2$Rodent[prop_dat2$Rodent>0]<-1
prop_dat2$Suidae[prop_dat2$Suidae>0] <- 1
prop_dat2$Ungulate[prop_dat2$Ungulate>0]<-1
prop_dat2$Total <- prop_dat2$Ape + prop_dat2$Bat +prop_dat2$Bird +prop_dat2$BushBaby + prop_dat2$Carnivore +prop_dat2$Elephant +prop_dat2$Monkey +prop_dat2$Suidae+prop_dat2$Ungulate
prop_dat2$Total[prop_dat2$Total>0] <- 1

prop_dat3 <- prop_dat2 %>% group_by(DispoCode) %>% summarise(Abundance = n(),
                                                             Ape = sum(Ape),
                                                             Bat = sum(Bat),
                                                             Bird = sum(Bird),
                                                             BushBaby = sum(BushBaby),
                                                             Carnivore= sum(Carnivore),
                                                             Elephant = sum(Elephant),
                                                             Monkey = sum(Monkey),
                                                             #Rodent = sum(Rodent),
                                                             Suidae = sum(Suidae),
                                                             Ungulate = sum(Ungulate),
                                                             NDisp = sum(Total),
                                                             ApeProp = Ape/Abundance,
                                                             BatProp = Bat/Abundance,
                                                            BirdProp = Bird/Abundance,
                                                             BushBabyProp = BushBaby/Abundance,
                                                             CarnivoreProp = Carnivore/Abundance,
                                                             ElephantProp = Elephant/Abundance,
                                                             MonkeyProp = Monkey/Abundance,
                                                             #RodentProp = Rodent/Abundance,
                                                             SuidaeProp = Suidae/Abundance,
                                                             UngulateProp = Ungulate/Abundance,
                                                             Prop_disp = NDisp/Abundance)

richness_list[[i]] <- div_values_interaction$richness
alpha_list[[i]] <- div_values_interaction$alpha
beta_list[[i]] <- div_values_interaction$beta
prop_list[[i]] <- prop_dat3$Prop_disp
n_list[[i]] <- prop_dat3$NDisp
ape_list[[i]] <- prop_dat3$Ape
ape_prop_list[[i]] <- prop_dat3$ApeProp
bat_list[[i]] <- prop_dat3$Bat
bat_prop_list[[i]] <- prop_dat3$BatProp
bird_list[[i]] <- prop_dat3$Bird
bird_prop_list[[i]] <- prop_dat3$BirdProp
bush_list[[i]] <- prop_dat3$BushBaby
bush_prop_list[[i]] <- prop_dat3$BushBabyProp
carnivore_list[[i]] <- prop_dat3$Carnivore
carnivore_prop_list[[i]] <- prop_dat3$CarnivoreProp
elephant_list[[i]] <- prop_dat3$Elephant
elephant_prop_list[[i]] <- prop_dat3$ElephantProp
monkey_list[[i]] <- prop_dat3$Monkey
monkey_prop_list[[i]] <- prop_dat3$MonkeyProp
#rodent_list[[i]] <- prop_dat3$Rodent
#rodent_prop_list[[i]] <- prop_dat3$RodentProp
suidae_list[[i]] <- prop_dat3$Suidae
suidae_prop_list[[i]] <- prop_dat3$SuidaeProp
ungulate_list[[i]] <- prop_dat3$Ungulate
ungulate_prop_list[[i]] <- prop_dat3$UngulateProp

}

interaction_draws <- data.frame(rep(div_values_interaction$DispoCode, 25), unlist(richness_list), unlist(alpha_list), unlist(beta_list), unlist(prop_list), unlist(n_list),
        unlist(ape_list),unlist(bat_list), unlist(bird_list), unlist(bush_list), unlist(carnivore_list), unlist(elephant_list), unlist(monkey_list), unlist(suidae_list),unlist(ungulate_list),
        unlist(ape_prop_list),unlist(bat_prop_list), unlist(bird_prop_list), unlist(bush_prop_list), unlist(carnivore_prop_list), unlist(elephant_prop_list), unlist(monkey_prop_list), unlist(suidae_prop_list), unlist(ungulate_prop_list))

colnames(interaction_draws) <- c("DispoCode", "richness", "alpha", "beta", "prop", "n", "ape", "bat", "bird", "bush", "carnivore", "elephant", "monkey",  "suidae", "ungulate",
                                 "ape_prop", "bat_prop", "bird_prop", "bush_prop", "carnivore_prop", "elephant_prop", "monkey_prop", "suidae_prop", "ungulate_prop")

write.csv(interaction_draws, "interaction_draws_norodents.csv")


```

```{r Calculate Interaction Diversity}
richness_list <- as.list(NULL)
alpha_list <- as.list(NULL)
beta_list <- as.list(NULL)
prop_list <- as.list(NULL)
n_list <- as.list(NULL)
ape_list <- as.list(NULL)
ape_prop_list <- as.list(NULL)
bat_list <- as.list(NULL)
bat_prop_list <- as.list(NULL)
bird_list <- as.list(NULL)
bird_prop_list <- as.list(NULL)
bush_list <- as.list(NULL)
bush_prop_list <- as.list(NULL)
carnivore_list <- as.list(NULL)
carnivore_prop_list <- as.list(NULL)
elephant_list <- as.list(NULL)
elephant_prop_list <- as.list(NULL)
monkey_list <- as.list(NULL)
monkey_prop_list <- as.list(NULL)
#rodent_list <- as.list(NULL)
#rodent_prop_list <- as.list(NULL)
suidae_list <- as.list(NULL)
suidae_prop_list <- as.list(NULL)
ungulate_list <- as.list(NULL)
ungulate_prop_list <- as.list(NULL)

for(i in 1:25){

tdat_interaction <- tdat2 %>% select(X,DispoCode, Genus, Agapornis_swindernianus:Zosterops_senegalensis) %>% pivot_longer(names_to = "Animal", values_to = "InteractionProbability", cols = Agapornis_swindernianus:Zosterops_senegalensis)

tdat_interaction$InteractionProbability <- rbinom(nrow(tdat_interaction), 1 , tdat_interaction$InteractionProbability) #draw from probability distribution
  
tdat_interaction2 <- tdat_interaction %>% filter(InteractionProbability ==1) %>% unite("Interaction", Genus:Animal, sep="_")

#Richness
div_values_interaction <- tdat_interaction2 %>%select(DispoCode, Interaction) %>%group_by(DispoCode) %>% summarise(richness = length(unique(Interaction))) 

#Alpha Diversity
tdat3_interaction <- tdat_interaction2%>% group_by(DispoCode, Interaction) %>% summarise(InteractionProbability = sum(InteractionProbability)) %>% pivot_wider(names_from = Interaction, values_from = InteractionProbability)
tdat3_interaction[is.na(tdat3_interaction)]<-0
tdat3_interaction<- as.data.frame(tdat3_interaction)
rownames(tdat3_interaction)<- tdat3_interaction$DispoCode
tdat3_interaction <- tdat3_interaction[,-1]
diversity_values_interaction <- vegan::diversity(tdat3_interaction)#calculate alpha diversity values
div_values_interaction$alpha <- diversity_values_interaction

#Beta Diversity
beta_div_interaction <- beta.div(tdat3_interaction, "hellinger", nperm=1000) #calculate beta diversity
beta_values_interaction <- beta_div_interaction$LCBD# calculate local contributions to beta diversity
div_values_interaction$beta <- beta_values_interaction

#Proportion of trees with frugivore interaction

prop_dat2 <- left_join(tdat_interaction, animal_taxa[,c(2,4)], by = "Animal") %>% dplyr::select(DispoCode, InteractionProbability, Taxa,X) %>% group_by(DispoCode, X, Taxa) %>% summarise(Interaction = sum(InteractionProbability)) %>% pivot_wider(names_from = Taxa, values_from = Interaction) %>% dplyr::select(-X)
prop_dat2 <- prop_dat2[,-1]
prop_dat2$Ape[prop_dat2$Ape>0]<-1
prop_dat2$Bat[prop_dat2$Bat>0]<-1
prop_dat2$Bird[prop_dat2$Bird>0]<-1
prop_dat2$BushBaby[prop_dat2$BushBaby>0]<-1
prop_dat2$Carnivore[prop_dat2$Carnivore>0]<-1
prop_dat2$Elephant[prop_dat2$Elephant>0]<-1
prop_dat2$Monkey[prop_dat2$Monkey>0]<-1
#prop_dat2$Rodent[prop_dat2$Rodent>0]<-1
prop_dat2$Suidae[prop_dat2$Suidae>0] <- 1
prop_dat2$Ungulate[prop_dat2$Ungulate>0]<-1
prop_dat2$Total <- prop_dat2$Ape + prop_dat2$Bat +prop_dat2$Bird +prop_dat2$BushBaby + prop_dat2$Carnivore +prop_dat2$Elephant +prop_dat2$Monkey +prop_dat2$Suidae+prop_dat2$Ungulate
prop_dat2$Total[prop_dat2$Total>0] <- 1

prop_dat3 <- prop_dat2 %>% group_by(DispoCode) %>% summarise(Abundance = n(),
                                                             Ape = sum(Ape),
                                                             Bat = sum(Bat),
                                                             Bird = sum(Bird),
                                                             BushBaby = sum(BushBaby),
                                                             Carnivore= sum(Carnivore),
                                                             Elephant = sum(Elephant),
                                                             Monkey = sum(Monkey),
                                                             #Rodent = sum(Rodent),
                                                             Suidae = sum(Suidae),
                                                             Ungulate = sum(Ungulate),
                                                             NDisp = sum(Total),
                                                             ApeProp = Ape/Abundance,
                                                             BatProp = Bat/Abundance,
                                                            BirdProp = Bird/Abundance,
                                                             BushBabyProp = BushBaby/Abundance,
                                                             CarnivoreProp = Carnivore/Abundance,
                                                             ElephantProp = Elephant/Abundance,
                                                             MonkeyProp = Monkey/Abundance,
                                                             #RodentProp = Rodent/Abundance,
                                                             SuidaeProp = Suidae/Abundance,
                                                             UngulateProp = Ungulate/Abundance,
                                                             Prop_disp = NDisp/Abundance)

richness_list[[i]] <- div_values_interaction$richness
alpha_list[[i]] <- div_values_interaction$alpha
beta_list[[i]] <- div_values_interaction$beta
prop_list[[i]] <- prop_dat3$Prop_disp
n_list[[i]] <- prop_dat3$NDisp
ape_list[[i]] <- prop_dat3$Ape
ape_prop_list[[i]] <- prop_dat3$ApeProp
bat_list[[i]] <- prop_dat3$Bat
bat_prop_list[[i]] <- prop_dat3$BatProp
bird_list[[i]] <- prop_dat3$Bird
bird_prop_list[[i]] <- prop_dat3$BirdProp
bush_list[[i]] <- prop_dat3$BushBaby
bush_prop_list[[i]] <- prop_dat3$BushBabyProp
carnivore_list[[i]] <- prop_dat3$Carnivore
carnivore_prop_list[[i]] <- prop_dat3$CarnivoreProp
elephant_list[[i]] <- prop_dat3$Elephant
elephant_prop_list[[i]] <- prop_dat3$ElephantProp
monkey_list[[i]] <- prop_dat3$Monkey
monkey_prop_list[[i]] <- prop_dat3$MonkeyProp
#rodent_list[[i]] <- prop_dat3$Rodent
#rodent_prop_list[[i]] <- prop_dat3$RodentProp
suidae_list[[i]] <- prop_dat3$Suidae
suidae_prop_list[[i]] <- prop_dat3$SuidaeProp
ungulate_list[[i]] <- prop_dat3$Ungulate
ungulate_prop_list[[i]] <- prop_dat3$UngulateProp

}

interaction_draws2 <- data.frame(rep(div_values_interaction$DispoCode, 25), unlist(richness_list), unlist(alpha_list), unlist(beta_list), unlist(prop_list), unlist(n_list),
        unlist(ape_list),unlist(bat_list), unlist(bird_list), unlist(bush_list), unlist(carnivore_list), unlist(elephant_list), unlist(monkey_list), unlist(suidae_list),unlist(ungulate_list),
        unlist(ape_prop_list),unlist(bat_prop_list), unlist(bird_prop_list), unlist(bush_prop_list), unlist(carnivore_prop_list), unlist(elephant_prop_list), unlist(monkey_prop_list), unlist(suidae_prop_list), unlist(ungulate_prop_list))

colnames(interaction_draws2) <- c("DispoCode", "richness", "alpha", "beta", "prop", "n", "ape", "bat", "bird", "bush", "carnivore", "elephant", "monkey",  "suidae", "ungulate",
                                 "ape_prop", "bat_prop", "bird_prop", "bush_prop", "carnivore_prop", "elephant_prop", "monkey_prop", "suidae_prop", "ungulate_prop")

write.csv(interaction_draws2, "interaction_draws_norodents_b.csv")


```

```{r Calculate Interaction Diversity}
richness_list <- as.list(NULL)
alpha_list <- as.list(NULL)
beta_list <- as.list(NULL)
prop_list <- as.list(NULL)
n_list <- as.list(NULL)
ape_list <- as.list(NULL)
ape_prop_list <- as.list(NULL)
bat_list <- as.list(NULL)
bat_prop_list <- as.list(NULL)
bird_list <- as.list(NULL)
bird_prop_list <- as.list(NULL)
bush_list <- as.list(NULL)
bush_prop_list <- as.list(NULL)
carnivore_list <- as.list(NULL)
carnivore_prop_list <- as.list(NULL)
elephant_list <- as.list(NULL)
elephant_prop_list <- as.list(NULL)
monkey_list <- as.list(NULL)
monkey_prop_list <- as.list(NULL)
#rodent_list <- as.list(NULL)
#rodent_prop_list <- as.list(NULL)
suidae_list <- as.list(NULL)
suidae_prop_list <- as.list(NULL)
ungulate_list <- as.list(NULL)
ungulate_prop_list <- as.list(NULL)

for(i in 1:25){

tdat_interaction <- tdat2 %>% select(X,DispoCode, Genus, Agapornis_swindernianus:Zosterops_senegalensis) %>% pivot_longer(names_to = "Animal", values_to = "InteractionProbability", cols = Agapornis_swindernianus:Zosterops_senegalensis)

tdat_interaction$InteractionProbability <- rbinom(nrow(tdat_interaction), 1 , tdat_interaction$InteractionProbability) #draw from probability distribution
  
tdat_interaction2 <- tdat_interaction %>% filter(InteractionProbability ==1) %>% unite("Interaction", Genus:Animal, sep="_")

#Richness
div_values_interaction <- tdat_interaction2 %>%select(DispoCode, Interaction) %>%group_by(DispoCode) %>% summarise(richness = length(unique(Interaction))) 

#Alpha Diversity
tdat3_interaction <- tdat_interaction2%>% group_by(DispoCode, Interaction) %>% summarise(InteractionProbability = sum(InteractionProbability)) %>% pivot_wider(names_from = Interaction, values_from = InteractionProbability)
tdat3_interaction[is.na(tdat3_interaction)]<-0
tdat3_interaction<- as.data.frame(tdat3_interaction)
rownames(tdat3_interaction)<- tdat3_interaction$DispoCode
tdat3_interaction <- tdat3_interaction[,-1]
diversity_values_interaction <- vegan::diversity(tdat3_interaction)#calculate alpha diversity values
div_values_interaction$alpha <- diversity_values_interaction

#Beta Diversity
beta_div_interaction <- beta.div(tdat3_interaction, "hellinger", nperm=1000) #calculate beta diversity
beta_values_interaction <- beta_div_interaction$LCBD# calculate local contributions to beta diversity
div_values_interaction$beta <- beta_values_interaction

#Proportion of trees with frugivore interaction

prop_dat2 <- left_join(tdat_interaction, animal_taxa[,c(2,4)], by = "Animal") %>% dplyr::select(DispoCode, InteractionProbability, Taxa,X) %>% group_by(DispoCode, X, Taxa) %>% summarise(Interaction = sum(InteractionProbability)) %>% pivot_wider(names_from = Taxa, values_from = Interaction) %>% dplyr::select(-X)
prop_dat2 <- prop_dat2[,-1]
prop_dat2$Ape[prop_dat2$Ape>0]<-1
prop_dat2$Bat[prop_dat2$Bat>0]<-1
prop_dat2$Bird[prop_dat2$Bird>0]<-1
prop_dat2$BushBaby[prop_dat2$BushBaby>0]<-1
prop_dat2$Carnivore[prop_dat2$Carnivore>0]<-1
prop_dat2$Elephant[prop_dat2$Elephant>0]<-1
prop_dat2$Monkey[prop_dat2$Monkey>0]<-1
#prop_dat2$Rodent[prop_dat2$Rodent>0]<-1
prop_dat2$Suidae[prop_dat2$Suidae>0] <- 1
prop_dat2$Ungulate[prop_dat2$Ungulate>0]<-1
prop_dat2$Total <- prop_dat2$Ape + prop_dat2$Bat +prop_dat2$Bird +prop_dat2$BushBaby + prop_dat2$Carnivore +prop_dat2$Elephant +prop_dat2$Monkey +prop_dat2$Suidae+prop_dat2$Ungulate
prop_dat2$Total[prop_dat2$Total>0] <- 1

prop_dat3 <- prop_dat2 %>% group_by(DispoCode) %>% summarise(Abundance = n(),
                                                             Ape = sum(Ape),
                                                             Bat = sum(Bat),
                                                             Bird = sum(Bird),
                                                             BushBaby = sum(BushBaby),
                                                             Carnivore= sum(Carnivore),
                                                             Elephant = sum(Elephant),
                                                             Monkey = sum(Monkey),
                                                             #Rodent = sum(Rodent),
                                                             Suidae = sum(Suidae),
                                                             Ungulate = sum(Ungulate),
                                                             NDisp = sum(Total),
                                                             ApeProp = Ape/Abundance,
                                                             BatProp = Bat/Abundance,
                                                            BirdProp = Bird/Abundance,
                                                             BushBabyProp = BushBaby/Abundance,
                                                             CarnivoreProp = Carnivore/Abundance,
                                                             ElephantProp = Elephant/Abundance,
                                                             MonkeyProp = Monkey/Abundance,
                                                             #RodentProp = Rodent/Abundance,
                                                             SuidaeProp = Suidae/Abundance,
                                                             UngulateProp = Ungulate/Abundance,
                                                             Prop_disp = NDisp/Abundance)

richness_list[[i]] <- div_values_interaction$richness
alpha_list[[i]] <- div_values_interaction$alpha
beta_list[[i]] <- div_values_interaction$beta
prop_list[[i]] <- prop_dat3$Prop_disp
n_list[[i]] <- prop_dat3$NDisp
ape_list[[i]] <- prop_dat3$Ape
ape_prop_list[[i]] <- prop_dat3$ApeProp
bat_list[[i]] <- prop_dat3$Bat
bat_prop_list[[i]] <- prop_dat3$BatProp
bird_list[[i]] <- prop_dat3$Bird
bird_prop_list[[i]] <- prop_dat3$BirdProp
bush_list[[i]] <- prop_dat3$BushBaby
bush_prop_list[[i]] <- prop_dat3$BushBabyProp
carnivore_list[[i]] <- prop_dat3$Carnivore
carnivore_prop_list[[i]] <- prop_dat3$CarnivoreProp
elephant_list[[i]] <- prop_dat3$Elephant
elephant_prop_list[[i]] <- prop_dat3$ElephantProp
monkey_list[[i]] <- prop_dat3$Monkey
monkey_prop_list[[i]] <- prop_dat3$MonkeyProp
#rodent_list[[i]] <- prop_dat3$Rodent
#rodent_prop_list[[i]] <- prop_dat3$RodentProp
suidae_list[[i]] <- prop_dat3$Suidae
suidae_prop_list[[i]] <- prop_dat3$SuidaeProp
ungulate_list[[i]] <- prop_dat3$Ungulate
ungulate_prop_list[[i]] <- prop_dat3$UngulateProp

}

interaction_draws3 <- data.frame(rep(div_values_interaction$DispoCode, 25), unlist(richness_list), unlist(alpha_list), unlist(beta_list), unlist(prop_list), unlist(n_list),
        unlist(ape_list),unlist(bat_list), unlist(bird_list), unlist(bush_list), unlist(carnivore_list), unlist(elephant_list), unlist(monkey_list), unlist(suidae_list),unlist(ungulate_list),
        unlist(ape_prop_list),unlist(bat_prop_list), unlist(bird_prop_list), unlist(bush_prop_list), unlist(carnivore_prop_list), unlist(elephant_prop_list), unlist(monkey_prop_list), unlist(suidae_prop_list), unlist(ungulate_prop_list))

colnames(interaction_draws3) <- c("DispoCode", "richness", "alpha", "beta", "prop", "n", "ape", "bat", "bird", "bush", "carnivore", "elephant", "monkey",  "suidae", "ungulate",
                                 "ape_prop", "bat_prop", "bird_prop", "bush_prop", "carnivore_prop", "elephant_prop", "monkey_prop", "suidae_prop", "ungulate_prop")

write.csv(interaction_draws3, "interaction_draws_norodents_c.csv")


```

```{r Calculate Interaction Diversity}
richness_list <- as.list(NULL)
alpha_list <- as.list(NULL)
beta_list <- as.list(NULL)
prop_list <- as.list(NULL)
n_list <- as.list(NULL)
ape_list <- as.list(NULL)
ape_prop_list <- as.list(NULL)
bat_list <- as.list(NULL)
bat_prop_list <- as.list(NULL)
bird_list <- as.list(NULL)
bird_prop_list <- as.list(NULL)
bush_list <- as.list(NULL)
bush_prop_list <- as.list(NULL)
carnivore_list <- as.list(NULL)
carnivore_prop_list <- as.list(NULL)
elephant_list <- as.list(NULL)
elephant_prop_list <- as.list(NULL)
monkey_list <- as.list(NULL)
monkey_prop_list <- as.list(NULL)
#rodent_list <- as.list(NULL)
#rodent_prop_list <- as.list(NULL)
suidae_list <- as.list(NULL)
suidae_prop_list <- as.list(NULL)
ungulate_list <- as.list(NULL)
ungulate_prop_list <- as.list(NULL)

for(i in 1:25){

tdat_interaction <- tdat2 %>% select(X,DispoCode, Genus, Agapornis_swindernianus:Zosterops_senegalensis) %>% pivot_longer(names_to = "Animal", values_to = "InteractionProbability", cols = Agapornis_swindernianus:Zosterops_senegalensis)

tdat_interaction$InteractionProbability <- rbinom(nrow(tdat_interaction), 1 , tdat_interaction$InteractionProbability) #draw from probability distribution
  
tdat_interaction2 <- tdat_interaction %>% filter(InteractionProbability ==1) %>% unite("Interaction", Genus:Animal, sep="_")

#Richness
div_values_interaction <- tdat_interaction2 %>%select(DispoCode, Interaction) %>%group_by(DispoCode) %>% summarise(richness = length(unique(Interaction))) 

#Alpha Diversity
tdat3_interaction <- tdat_interaction2%>% group_by(DispoCode, Interaction) %>% summarise(InteractionProbability = sum(InteractionProbability)) %>% pivot_wider(names_from = Interaction, values_from = InteractionProbability)
tdat3_interaction[is.na(tdat3_interaction)]<-0
tdat3_interaction<- as.data.frame(tdat3_interaction)
rownames(tdat3_interaction)<- tdat3_interaction$DispoCode
tdat3_interaction <- tdat3_interaction[,-1]
diversity_values_interaction <- vegan::diversity(tdat3_interaction)#calculate alpha diversity values
div_values_interaction$alpha <- diversity_values_interaction

#Beta Diversity
beta_div_interaction <- beta.div(tdat3_interaction, "hellinger", nperm=1000) #calculate beta diversity
beta_values_interaction <- beta_div_interaction$LCBD# calculate local contributions to beta diversity
div_values_interaction$beta <- beta_values_interaction

#Proportion of trees with frugivore interaction

prop_dat2 <- left_join(tdat_interaction, animal_taxa[,c(2,4)], by = "Animal") %>% dplyr::select(DispoCode, InteractionProbability, Taxa,X) %>% group_by(DispoCode, X, Taxa) %>% summarise(Interaction = sum(InteractionProbability)) %>% pivot_wider(names_from = Taxa, values_from = Interaction) %>% dplyr::select(-X)
prop_dat2 <- prop_dat2[,-1]
prop_dat2$Ape[prop_dat2$Ape>0]<-1
prop_dat2$Bat[prop_dat2$Bat>0]<-1
prop_dat2$Bird[prop_dat2$Bird>0]<-1
prop_dat2$BushBaby[prop_dat2$BushBaby>0]<-1
prop_dat2$Carnivore[prop_dat2$Carnivore>0]<-1
prop_dat2$Elephant[prop_dat2$Elephant>0]<-1
prop_dat2$Monkey[prop_dat2$Monkey>0]<-1
#prop_dat2$Rodent[prop_dat2$Rodent>0]<-1
prop_dat2$Suidae[prop_dat2$Suidae>0] <- 1
prop_dat2$Ungulate[prop_dat2$Ungulate>0]<-1
prop_dat2$Total <- prop_dat2$Ape + prop_dat2$Bat +prop_dat2$Bird +prop_dat2$BushBaby + prop_dat2$Carnivore +prop_dat2$Elephant +prop_dat2$Monkey +prop_dat2$Suidae+prop_dat2$Ungulate
prop_dat2$Total[prop_dat2$Total>0] <- 1

prop_dat3 <- prop_dat2 %>% group_by(DispoCode) %>% summarise(Abundance = n(),
                                                             Ape = sum(Ape),
                                                             Bat = sum(Bat),
                                                             Bird = sum(Bird),
                                                             BushBaby = sum(BushBaby),
                                                             Carnivore= sum(Carnivore),
                                                             Elephant = sum(Elephant),
                                                             Monkey = sum(Monkey),
                                                             #Rodent = sum(Rodent),
                                                             Suidae = sum(Suidae),
                                                             Ungulate = sum(Ungulate),
                                                             NDisp = sum(Total),
                                                             ApeProp = Ape/Abundance,
                                                             BatProp = Bat/Abundance,
                                                            BirdProp = Bird/Abundance,
                                                             BushBabyProp = BushBaby/Abundance,
                                                             CarnivoreProp = Carnivore/Abundance,
                                                             ElephantProp = Elephant/Abundance,
                                                             MonkeyProp = Monkey/Abundance,
                                                             #RodentProp = Rodent/Abundance,
                                                             SuidaeProp = Suidae/Abundance,
                                                             UngulateProp = Ungulate/Abundance,
                                                             Prop_disp = NDisp/Abundance)

richness_list[[i]] <- div_values_interaction$richness
alpha_list[[i]] <- div_values_interaction$alpha
beta_list[[i]] <- div_values_interaction$beta
prop_list[[i]] <- prop_dat3$Prop_disp
n_list[[i]] <- prop_dat3$NDisp
ape_list[[i]] <- prop_dat3$Ape
ape_prop_list[[i]] <- prop_dat3$ApeProp
bat_list[[i]] <- prop_dat3$Bat
bat_prop_list[[i]] <- prop_dat3$BatProp
bird_list[[i]] <- prop_dat3$Bird
bird_prop_list[[i]] <- prop_dat3$BirdProp
bush_list[[i]] <- prop_dat3$BushBaby
bush_prop_list[[i]] <- prop_dat3$BushBabyProp
carnivore_list[[i]] <- prop_dat3$Carnivore
carnivore_prop_list[[i]] <- prop_dat3$CarnivoreProp
elephant_list[[i]] <- prop_dat3$Elephant
elephant_prop_list[[i]] <- prop_dat3$ElephantProp
monkey_list[[i]] <- prop_dat3$Monkey
monkey_prop_list[[i]] <- prop_dat3$MonkeyProp
#rodent_list[[i]] <- prop_dat3$Rodent
#rodent_prop_list[[i]] <- prop_dat3$RodentProp
suidae_list[[i]] <- prop_dat3$Suidae
suidae_prop_list[[i]] <- prop_dat3$SuidaeProp
ungulate_list[[i]] <- prop_dat3$Ungulate
ungulate_prop_list[[i]] <- prop_dat3$UngulateProp

}

interaction_draws4 <- data.frame(rep(div_values_interaction$DispoCode, 25), unlist(richness_list), unlist(alpha_list), unlist(beta_list), unlist(prop_list), unlist(n_list),
        unlist(ape_list),unlist(bat_list), unlist(bird_list), unlist(bush_list), unlist(carnivore_list), unlist(elephant_list), unlist(monkey_list), unlist(suidae_list),unlist(ungulate_list),
        unlist(ape_prop_list),unlist(bat_prop_list), unlist(bird_prop_list), unlist(bush_prop_list), unlist(carnivore_prop_list), unlist(elephant_prop_list), unlist(monkey_prop_list), unlist(suidae_prop_list), unlist(ungulate_prop_list))

colnames(interaction_draws4) <- c("DispoCode", "richness", "alpha", "beta", "prop", "n", "ape", "bat", "bird", "bush", "carnivore", "elephant", "monkey",  "suidae", "ungulate",
                                 "ape_prop", "bat_prop", "bird_prop", "bush_prop", "carnivore_prop", "elephant_prop", "monkey_prop", "suidae_prop", "ungulate_prop")

write.csv(interaction_draws4, "interaction_draws_norodents_d.csv")


```

```{r Calculate Interaction Diversity}

interaction_draws <- read.csv( "interaction_draws_norodents.csv")
interaction_draws_b <- read.csv( "interaction_draws_norodents_b.csv")
interaction_draws_c <- read.csv( "interaction_draws_norodents_c.csv")
interaction_draws_d <- read.csv( "interaction_draws_norodents_d.csv")
interaction_draws_e <- rbind(interaction_draws, interaction_draws_b, interaction_draws_c, interaction_draws_d)

interaction_draws2 <- interaction_draws_e %>% group_by(DispoCode) %>% summarise(richness=mean(richness), alpha=mean(alpha), beta=mean(beta), proportion = mean(prop), n= mean(n),
                                                                              ape=mean(ape), bat =mean(bat), bird=mean(bird), bush=mean(bush), carnivore=mean(carnivore), elephant=mean(elephant), monkey=mean(monkey),  suidae=mean(suidae),ungulate = mean(ungulate),
                                                                              ape_prop=mean(ape_prop), bat_prop =mean(bat_prop), bird_prop=mean(bird_prop), bush_prop=mean(bush_prop), carnivore_prop=mean(carnivore_prop), elephant_prop=mean(elephant_prop), monkey_prop=mean(monkey_prop),  suidae_prop=mean(suidae_prop), ungulate_prop=mean(ungulate_prop))

div_values_interaction <- interaction_draws2 


calculate_mean_and_confidence_intervals <- function(proportions_list) {
  # Create a list to store the results
  results_list <- list()
  
  # Function to calculate 95% CI for a proportion using normal approximation
  ci_normal_approx <- function(p, n, conf.level = 0.95) {
    alpha <- 1 - conf.level
    z <- qnorm(1 - alpha / 2)
    se <- sqrt((p * (1 - p)) / n)
    lower <- p - z * se
    upper <- p + z * se
    return(c(lower, upper))
  }
  
  # Iterate through each list of proportions
  for (j in 1:length(proportions_list)) {
    proportions <- proportions_list[[j]]
    
    # Calculate the mean proportion
    mean_proportion <- mean(proportions)
    
    # Assuming each proportion is out of 100 trials
    n <- round(length(proportions) * 100,0)
    
    # Calculate the confidence interval for the mean proportion
    ci <- ci_normal_approx(mean_proportion, n)
    
    # Store the results for the current list of proportions
    results_list[[j]] <- data.frame(
      List = j,
      Mean_Proportion = mean_proportion,
      CI_Lower = ci[1],
      CI_Upper = ci[2]
    )
  }
  
  # Combine results into a single data frame
  results_df <- do.call(rbind, results_list)
  
  return(results_df)
}

proportions_list <- list(div_values_interaction$proportion, div_values_interaction$ape_prop, div_values_interaction$bat_prop,
                         div_values_interaction$bird_prop, div_values_interaction$bush_prop, div_values_interaction$carnivore_prop,
                         div_values_interaction$elephant_prop,div_values_interaction$monkey_prop, 
                         div_values_interaction$suidae_prop, div_values_interaction$ungulate_prop)

results <- calculate_mean_and_confidence_intervals(proportions_list)

results$Taxa <- c("Total", "Ape", "Bat", "Bird", "Bush Baby", "Carnivore", "Elephant", "Monkey",  "Bush Pig", "Ungulate")

results$Taxa <- factor(results$Taxa, levels = results$Taxa[order(results$Mean_Proportion, decreasing = FALSE)])


#div_values_interaction2 <- interaction_draws2 %>% dplyr::select(proportion, ape_prop, bat_prop, bird_prop, bush_prop, carnivore_prop, elephant_prop, monkey_prop, rodent_prop, suidae_prop) %>% pivot_longer(names_to = "Type", values_to = "Proportion", cols = proportion:suidae_prop) %>% 

mean(interaction_draws2$proportion)
sd(interaction_draws2$proportion)

interaction_draws3 <- interaction_draws2 %>% select(DispoCode, richness, alpha, beta, proportion, n) %>% summarise(richness = mean(richness), alpha = mean(alpha), beta = mean(beta), proportion = mean(proportion), n = mean(n))


```

```{r Spatial Autoregressive Models}

coords <- cbind(div_meta_interaction$longitude, div_meta_interaction$latitude)
nb <- knearneigh(coords, k = 4)
nb <- knn2nb(nb)
lw <- nb2listw(nb, style = "W")

library(spatialreg)

div_meta_interaction <- left_join(div_values_interaction, metadata, by = "DispoCode") # add metadata
div_meta_interaction <- div_meta_interaction[!is.na(div_meta_interaction$Elephant),] #remove plots that do not have values of elephant activity
div_meta_interaction$Elephant[div_meta_interaction$Elephant=="Ancienne piste/pas d'activite"] <- "1"
div_meta_interaction$Elephant[div_meta_interaction$Elephant=="Active"] <- "1"
div_meta_interaction$Elephant[div_meta_interaction$Elephant=="Pas d'indice"] <- "0"
div_meta_interaction$Succ2 <- factor(div_meta_interaction$Succ2, levels= c("Prm", "Sec", "Exp"))


div_meta_interaction <- div_meta_interaction %>% drop_na(NightLights)


richness_sar <- errorTemprichness_sar <- errorsarlm(richness ~ Elephant + VillDist + Temp + Succ2 + Prec +
                        Latitude + SoilPCA + NightLights + PopDensity,
                      data = div_meta_interaction,
                      listw = lw)
richness_sar_summary <- summary(richness_sar)

alpha_sar <- errorsarlm(alpha ~ Elephant + VillDist + Temp + Succ2 + Prec +
                        Latitude + SoilPCA + NightLights + PopDensity,
                      data = div_meta_interaction,
                      listw = lw)
alpha_sar_summary <-summary(alpha_sar)

beta_sar <- errorsarlm(beta ~ Elephant + VillDist + Temp + Succ2 + Prec +
                        Latitude + SoilPCA + NightLights + PopDensity,
                      data = div_meta_interaction,
                      listw = lw)
beta_sar_summary <-summary(beta_sar)

n_sar <- errorsarlm(n ~ Elephant + VillDist + Temp + Succ2 + Prec +
                        Latitude + SoilPCA + NightLights + PopDensity,
                      data = div_meta_interaction,
                      listw = lw)
n_sar_summary <-summary(n_sar)


library(mgcv)

#can't do a classic spatial model for binomial data, so do a GAM with a spatial smooth instead

div_meta_interaction$n_round <- round(div_meta_interaction$n,0)
div_meta_interaction$n_opp <- div_meta_interaction$abundance -div_meta_interaction$n_round 
div_meta_interaction2 <- div_meta_interaction %>% select(DispoCode,n_round, n_opp,abundance, Elephant, VillDist, Temp, Succ2, Prec, Latitude, SoilPCA,NightLights,PopDensity, Latitude, Longitude) %>% drop_na()


gam_binom <- gam(
  cbind(n_round, n_opp) ~ Elephant + VillDist + Temp + Succ2 + Prec +
   SoilPCA + NightLights + PopDensity +
    s(Longitude, Latitude, bs = "tp"),          # spatial smooth
  data = div_meta_interaction2,
  family = binomial(link = "logit"),
  method = "REML"
)

binom_sar_summary <-summary(gam_binom)

library(broom)

binom_sar_summary <- tidy(gam_binom, parametric = TRUE) %>%
  filter(term != "(Intercept)") 


```

```{r Interaction Diversity Plots}

richness_df_interaction <- as.data.frame(richness_sar_summary$Coef)
richness_df_interaction$Variable <- rownames(richness_df_interaction)
richness_df_interaction$Type <- "Richness"

alpha_df_interaction <- as.data.frame(alpha_sar_summary$Coef)
alpha_df_interaction$Variable <- rownames(alpha_df_interaction)
alpha_df_interaction$Type <- "Alpha Diversity"

beta_df_interaction <- as.data.frame(beta_sar_summary$Coef)
beta_df_interaction$Variable <- rownames(beta_df_interaction)
beta_df_interaction$Type <- "Beta Diversity"

proportion_df_interaction <- as.data.frame(binom_sar_summary)
proportion_df_interaction$Variable <- proportion_df_interaction$term
proportion_df_interaction$Type <- "Proportion Dispersed"
proportion_df_interaction <- proportion_df_interaction[,-1]
colnames(proportion_df_interaction) <- colnames(beta_df_interaction)

n_df_interaction <- as.data.frame(n_sar_summary$Coef)
n_df_interaction$Variable <- rownames(n_df_interaction)
n_df_interaction$Type <- "Abundance Dispersed"

taxonomic_div_interaction <- rbind(richness_df_interaction, alpha_df_interaction, beta_df_interaction, proportion_df_interaction, n_df_interaction)
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Elephant1"]<- "Ele. Act."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="VillDist"]<- "Vill. Dist."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Elev"]<- "Elev."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Latitude"]<- "Lat."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Succ2Sec"]<- "Secondary"
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Succ2Exp"]<- "Logged"
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Temp"]<- "Temp."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="Prec"]<- "Prec."
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="SoilPCA"]<- "Soil PCA"
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="SoilPCA"]<- "Soil PCA"
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="NightLights"]<- "Night Lights"
taxonomic_div_interaction$Variable[taxonomic_div_interaction$Variable=="PopDensity"]<- "Pop. Density"

taxonomic_div_interaction$Lower <- taxonomic_div_interaction$Estimate - 1.96 * taxonomic_div_interaction$`Std. Error`
taxonomic_div_interaction$Upper <- taxonomic_div_interaction$Estimate + 1.96 * taxonomic_div_interaction$`Std. Error`
taxonomic_div_interaction$Lower90 <- taxonomic_div_interaction$Estimate - 1.644854 * taxonomic_div_interaction$`Std. Error`
taxonomic_div_interaction$Upper90 <- taxonomic_div_interaction$Estimate + 1.644854 * taxonomic_div_interaction$`Std. Error`

taxonomic_div_interaction <- taxonomic_div_interaction %>% filter(Variable != "(Intercept)")

taxonomic_div_interaction$VarType <- taxonomic_div_interaction$Variable
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Ele. Act."] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Lat."] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Elev."] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Temp."] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Prec."] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Soil PCA"] <- "Environmental"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Vill. Dist."] <- "Anthropogenic"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Logged"] <- "Anthropogenic"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Secondary"] <- "Anthropogenic"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Night Lights"] <- "Anthropogenic"
taxonomic_div_interaction$VarType[taxonomic_div_interaction$VarType=="Pop. Density"] <- "Anthropogenic"

taxonomic_div_interaction$Variable <- factor(taxonomic_div_interaction$Variable, levels = c("Ele. Act.", "Temp.","Prec.", "Elev.", "Lat.", "Soil PCA", "Vill. Dist.", "Secondary", "Logged", "Night Lights", "Pop. Density"))

richness_plot_interaction <- ggplot(data=taxonomic_div_interaction[taxonomic_div_interaction$Type=="Richness",], aes(x= Variable, y= Estimate, ymin=Lower, ymax=Upper, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate, ymin=Lower90, ymax=Upper90), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimated Effect on Richness")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(color='Variable Type') 

alpha_plot_interaction <- ggplot(data=taxonomic_div_interaction[taxonomic_div_interaction$Type=="Alpha Diversity",], aes(x= Variable, y= Estimate, ymin=Lower, ymax=Upper, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate, ymin=Lower90, ymax=Upper90), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimated Effect on alpha-Diversity")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ theme(legend.position = "none")

beta_plot_interaction <- ggplot(data=taxonomic_div_interaction[taxonomic_div_interaction$Type=="Beta Diversity",], aes(x= Variable, y= Estimate*1000, ymin=Lower*1000, ymax=Upper*1000, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate*1000, ymin=Lower90*1000, ymax=Upper90*1000), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimated Effect on beta-Diversity")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ theme(legend.position = "none")

proportion_plot_interaction <- ggplot(data=taxonomic_div_interaction[taxonomic_div_interaction$Type=="Proportion Dispersed",], aes(x= Variable, y= Estimate, ymin=Lower, ymax=Upper, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate, ymin=Lower90, ymax=Upper90), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Log-Odds of Frugivore Tree")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(color='Variable Type') 

n_plot_interaction <- ggplot(data=taxonomic_div_interaction[taxonomic_div_interaction$Type=="Abundance Dispersed",], aes(x= Variable, y= Estimate, ymin=Lower, ymax=Upper, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate, ymin=Lower90, ymax=Upper90), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimated Effect on # Frugivore Trees")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ theme(legend.position = "none")


diversity_plot_interaction <- ggarrange(richness_plot_interaction, alpha_plot_interaction, beta_plot_interaction, labels = c("a", "b", "c"), nrow=3, common.legend = TRUE)
plot_interaction <- ggarrange(proportion_plot_interaction, n_plot_interaction,labels = c("a", "b"), nrow=2, common.legend = TRUE)

```

```{r Calculate Taxonomic Diversity at Genus Level}

tdat2 <- tdat %>% filter(Genus != "Na")
(nrow(tdat)-nrow(tdat2))/nrow(tdat) 

metadata$VillDist <- scale(metadata$VillDist)
metadata$Temp <- scale(metadata$Temp)
metadata$Prec <- scale(metadata$Prec)
metadata$Latitude <- scale(metadata$Latitude)
metadata$T_OC <- scale(metadata$T_OC)
metadata$T_CEC_CLAY <- scale(metadata$T_CEC_CLAY)
metadata$Elev <- scale(metadata$Elev)

#Richness
div_values <- tdat2 %>% group_by(DispoCode) %>% summarise(richness = length(unique(Genus))) #calculate genus richness
mean(div_values$richness)

#Alpha Diversity
tdat3 <- tdat2 %>% select(Genus, DispoCode) %>% mutate(presence = 1) %>% group_by(DispoCode, Genus) %>% summarise(presence = sum(presence)) %>% pivot_wider(names_from = Genus, values_from = presence)
tdat3[is.na(tdat3)]<-0
tdat3<- as.data.frame(tdat3)
rownames(tdat3)<- tdat3$DispoCode
tdat3 <- tdat3[,-1]
class(tdat3)
diversity_values <- vegan::diversity(tdat3)#calculate alpha diversity values
div_values$alpha <- diversity_values

#Beta Diversity
beta_div <- beta.div(tdat3, "hellinger", nperm=1000) #calculate beta diversity
beta_values <- beta_div$LCBD# calculate local contributions to beta diversity
div_values$beta <- beta_values

```

```{r Evolutionary Distinctiveness of Ineractions}
#Plants
gcbd <- data.frame(beta_div$SCBD)
gcbd$Genus <- rownames(gcbd)
colnames(gcbd)[1] <- "gcbd"

plants <- gcbd %>% select(Genus)
plants <- getTaxonomy(plants$Genus)
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% select(species, genus, family)
y <- V.PhyloMaker::phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3
plot(tree_plants)

#EDi = EDm + EDp

EDi_list <- as.list(NULL)
DispoCode_list <- as.list(NULL)

for(i in 1:100){
#Animals 

ED_plants <- evol.distinct(tree_plants, type ="equal.splits", scale = FALSE, use.branch.lengths = TRUE)
ED_plants <- ED_plants %>% separate(Species, c("Genus", "sp"), sep = "_") %>% select(-sp) %>% rename(w_plants =w)
ED_animals <- evol.distinct(frug_tree, type ="equal.splits", scale = FALSE, use.branch.lengths = TRUE)
colnames(ED_animals)<- c("Animal", "w_animals")
ED_animals$Animal[ED_animals$Animal=="Loxodonta_africana"] <- "Loxodonta_cyclotis"
ED_animals$Animal[ED_animals$Animal=="Galagoides_demidovii"] <- "Galagoides_demidoff"
#ED_animals$Animal[ED_animals$Animal=="Loxodonta_africana"] <- "Loxodonta_cyclotis"

tdat_interaction <- tdat2 %>% select(DispoCode, Genus, Agapornis_swindernianus:Zosterops_senegalensis) %>% pivot_longer(names_to = "Animal", values_to = "InteractionProbability", cols = Agapornis_swindernianus:Zosterops_senegalensis)

tdat_interaction$InteractionProbability <- rbinom(nrow(tdat_interaction), 1 , tdat_interaction$InteractionProbability) #draw from probability distribution
tdat_interaction <- left_join(tdat_interaction, ED_plants, by = "Genus")
tdat_interaction <- left_join(tdat_interaction, ED_animals, by = "Animal")
  
tdat_interaction2 <- tdat_interaction %>% filter(InteractionProbability ==1) %>% unite("Interaction", Genus:Animal, sep="_")

tdat_interaction2$EDi <- tdat_interaction2$w_plants + tdat_interaction2$w_animals


EDi_list[[i]] <- tdat_interaction2$EDi
DispoCode_list[[i]] <- tdat_interaction2$DispoCode

}


#Evolutionary Distinctiveness of interactions
EDi_df <- data.frame(unlist(EDi_list), unlist(DispoCode_list))
colnames(EDi_df)<- c("EDi", "DispoCode")
EDi_df2 <- tdat_interaction2%>%drop_na() %>% group_by(DispoCode) %>% summarise(Mean_EDi = mean(EDi))
div_meta_interaction2 <- div_meta_interaction2 %>% left_join(EDi_df2, by ="DispoCode")


edi_sar <- errorsarlm(Mean_EDi ~ Elephant + VillDist + Temp + Succ2 + Prec +
                        Latitude + SoilPCA + NightLights + PopDensity,
                      data = div_meta_interaction2,
                      listw = lw)

edi_sar_summary <-summary(edi_sar)


edi_mod_summary <- as.data.frame(edi_sar_summary$Coef)

edi_mod_summary$Lower <- edi_mod_summary$Estimate - 1.96 * edi_mod_summary$`Std. Error`
edi_mod_summary$Upper <- edi_mod_summary$Estimate + 1.96 * edi_mod_summary$`Std. Error`
edi_mod_summary$Lower90 <- edi_mod_summary$Estimate - 1.644854 * edi_mod_summary$`Std. Error`
edi_mod_summary$Upper90 <- edi_mod_summary$Estimate + 1.644854 * edi_mod_summary$`Std. Error`

edi_mod_summary$Variable <- rownames(edi_mod_summary)
edi_mod_summary$Variable[edi_mod_summary$Variable=="Prec"] <- "Prec."
edi_mod_summary$Variable[edi_mod_summary$Variable=="SoilPCA"] <- "Soil PCA"
edi_mod_summary$Variable[edi_mod_summary$Variable=="VillDist"] <- "Vill. Dist."
edi_mod_summary$Variable[edi_mod_summary$Variable=="Temp"] <- "Temp."
edi_mod_summary$Variable[edi_mod_summary$Variable=="Elephant1"] <- "Ele. Act."
edi_mod_summary$Variable[edi_mod_summary$Variable=="Latitude"] <- "Lat."
edi_mod_summary$Variable[edi_mod_summary$Variable=="Succ2Sec"] <- "Secondary"
edi_mod_summary$Variable[edi_mod_summary$Variable=="Succ2Exp"] <- "Logged"
edi_mod_summary$Variable[edi_mod_summary$Variable=="PopDensity"] <- "Pop. Density"
edi_mod_summary$Variable[edi_mod_summary$Variable=="NightLights"] <- "Night Lights"

edi_mod_summary$VarType <- edi_mod_summary$Variable
edi_mod_summary$VarType[edi_mod_summary$VarType=="Ele. Act."] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Lat."] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Elev."] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Temp."] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Soil PCA"] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Prec."] <- "Environmental"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Vill. Dist."] <- "Anthropogenic"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Logged"] <- "Anthropogenic"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Secondary"] <- "Anthropogenic"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Pop. Density"] <- "Anthropogenic"
edi_mod_summary$VarType[edi_mod_summary$VarType=="Night Lights"] <- "Anthropogenic"

edi_mod_summary2 <- edi_mod_summary %>% filter(Variable != "(Intercept)")

edi_mod_summary2$Variable <- factor(edi_mod_summary2$Variable, levels = c("Ele. Act.", "Temp.","Prec.",  "Lat.", "Soil PCA", "Vill. Dist.", "Secondary", "Logged", "Night Lights", "Pop. Density"))

edi_plot <- ggplot(data=edi_mod_summary2, aes(x= Variable, y= Estimate, ymin=Lower, ymax=Upper, color=VarType))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(aes(color=VarType),position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Variable, y= Estimate, ymin=Lower90, ymax=Upper90, color=VarType), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimated Effect on ED")+
  theme(legend.position="bottom")+
  scale_color_manual(values = c("gold", "darkblue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
    labs(color='Variable Type') 


diversity_plot_interaction2 <- ggarrange(richness_plot_interaction, alpha_plot_interaction, beta_plot_interaction,edi_plot, labels = c("a", "b", "c", "d"), nrow=2,ncol=2, common.legend = TRUE)



write.csv(edi_mod_summary2, "edi_mod_summary2_norodents.csv")
write.csv(taxonomic_div_interaction, "taxonomic_div_interaction_norodents.csv")


```

