---
title: "NetworkDataCleaning"
author: "Camille"
date: "1/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load in Data and Packages}

#load packages
library(dplyr);library(igraph);library(bipartite);library(sna);library(network);library(ggplot2);library(ape);library(reshape2);library(ggnetwork);library(GGally);library(sand);library(maditr);library(textshape);library(sjstats);library(Hmisc);library(tidyverse); library(BIOMASS); library(sf);library(s2)

frug_dat_total_adj <- read.csv("~/Documents/GitHub/GabonDiversity/Data/frugivore_matrix.csv" )

#read network data
net_matrix <- frug_dat_total_adj
net_matrix <- net_matrix %>% rename(animal = X)

#read plot data
tdat_gabon <- read.csv("~/Documents/GitHub/FaunalDegradationAGB/Data/agb-trees-complete.csv")



```

```{r Species Ranges}

plot_coordinates <- read.csv("~/Documents/Projects/GabonAGB_NSF/plot-midpoints-complete.csv")

animals <- net_matrix$animal
animals <- gsub("_", " ", animals)
animals <- as.data.frame(animals)
colnames(animals) <- "sci_name"

animals[animals$binomial =="Cephalophus monticola",] <- "Philantomba monticola"

mammal_ranges <- st_read(
  "~/Documents/Projects/GabonAGB_NSF/MAMMALS_TERRESTRIAL_ONLY/MAMMALS_TERRESTRIAL_ONLY.shp")
mammal_range_names <- mammal_ranges$sci_name

bird_ranges <- st_read("~/Documents/Projects/GabonAGB_NSF/botw_gabon/botw_gabon.shp")
bird_range_names <- bird_ranges$sci_name

mammal_ranges2 <- merge(animals, mammal_ranges, by="sci_name")
bird_ranges2 <-merge(animals, bird_ranges, by ="sci_name")

mammal_ranges2 <- mammal_ranges2 %>% distinct()

mammal_ranges2 <- st_as_sf(mammal_ranges2)

plot_coordinates2 <- as.data.frame(plot_coordinates) %>% 
  st_as_sf(coords=c("Longitude","Latitude"), crs=4326, remove=FALSE)  

mammal_ranges2b <- sf::st_make_valid(mammal_ranges2)


bird_ranges2 <- bird_ranges2 %>% distinct()

bird_ranges2 <- st_as_sf(bird_ranges2)

plot_coordinates2 <- as.data.frame(plot_coordinates) %>% 
  st_as_sf(coords=c("Longitude","Latitude"), crs=4326, remove=FALSE)  


bird_ranges2b <- sf::st_make_valid(bird_ranges2)


mammal_ranges3 <- mammal_ranges2b %>% 
  group_by(sci_name) %>% 
  summarise(geometry = st_combine(geometry)) 

sf_use_s2(FALSE)

mammal_ranges_points <- st_join(plot_coordinates2, left = FALSE, mammal_ranges3["sci_name"])


mammal_ranges_points2 <- as.data.frame(mammal_ranges_points)
mammal_ranges_points2 <- mammal_ranges_points2 %>%
  select(DispoCode:sci_name)
mammal_ranges_points2$presence <- 1
mammal_ranges_points3 <- mammal_ranges_points2 %>%
  pivot_wider(names_from = sci_name, values_from = presence)
mammal_ranges_points3[is.na(mammal_ranges_points3)] <- 0

mammal_ranges_points4 <- mammal_ranges_points3



bird_ranges3 <- bird_ranges2b %>% 
  group_by(sci_name) %>% 
  summarise(geometry = st_combine(geometry)) 

bird_ranges_points <- st_join(plot_coordinates2, left = FALSE, bird_ranges3["sci_name"])

bird_ranges_points2 <- as.data.frame(bird_ranges_points)
bird_ranges_points2 <- bird_ranges_points2 %>%
  select(DispoCode:sci_name)
bird_ranges_points2$presence <- 1
bird_ranges_points3 <- bird_ranges_points2 %>%
  pivot_wider(names_from = sci_name, values_from = presence)
bird_ranges_points3[is.na(bird_ranges_points3)] <- 0

bird_ranges_points4 <- bird_ranges_points3[,-c(2:5)]

animal_ranges_points <- left_join(mammal_ranges_points4, bird_ranges_points4, by ="DispoCode")


```

```{r}
frug_network_dat <- t(as.data.frame(net_matrix))[-1,]
frug_network_dat<- as.data.frame(frug_network_dat )
colnames(frug_network_dat) <- frug_network_dat[1,]
frug_network_dat <- frug_network_dat[-1,]

mammal_range <- animal_ranges_points %>%
  pivot_longer(cols="Atherurus africanus":"Phylloscopus budongoensis" ,names_to = "animal", values_to="presence")
animals_in_plots <- unique(mammal_range$animal)
animals_in_plots  <- as.data.frame(animals_in_plots )
colnames(animals_in_plots) <- "animal"
animals_in_plots$animal <- gsub(" ", "_", animals_in_plots$animal)


net_matrix$animal[net_matrix$animal =="Cephalophus_monticola"] <- "Philantomba_monticola"
dispersal_dat <- merge(net_matrix, animals_in_plots, by="animal")
dispersal_dat2 <- dispersal_dat
rownames(dispersal_dat2) <- dispersal_dat2$animal
dispersal_dat2 <- dispersal_dat2[,-1]





dispersal_dat_t <- t(dispersal_dat)
dispersal_dat_t <- as.data.frame(dispersal_dat_t)
colnames(dispersal_dat_t) <- dispersal_dat_t[1,]
dispersal_dat_t  <- dispersal_dat_t[-c(1:2),]
dispersal_dat_t$Genus <- rownames(dispersal_dat_t)


```

```{r}
tdat_gabon$Species <- gsub(" ", "_", tdat_gabon$Espece)
tdat_frug <- left_join(tdat_gabon, dispersal_dat_t, by="Genus") %>% select(DispoCode, Espece,Genus, Famille, meanWD, H,D, AGB, Atherurus_africanus:Zosterops_senegalensis)

tdat_frug[is.na(tdat_frug)] <- 0

cols.num <- c(colnames(tdat_frug[9:154]))
tdat_frug[cols.num] <- sapply(tdat_frug[cols.num],as.numeric)



tdat_frug2 <- tdat_frug %>%
    mutate(NDispersed = select(., Atherurus_africanus:Zosterops_senegalensis)%>%
             rowSums(na.rm = TRUE))

tdat_frug2$DispersedBinary <- tdat_frug2$NDispersed
tdat_frug2$DispersedBinary[tdat_frug2$DispersedBinary>=1] <- 1

write.csv(tdat_frug2, "~/Documents/GitHub/GabonDiversity/Data/tdat_frug2.csv")


```

